/**
 * Regression safeguard: ensure analysis result is fetched at most once per analysis_id.
 */
import { renderHook, waitFor } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import React from 'react';
import { useAnalysisResult } from '../../app/queries/analysisResult';
import { AnalysisService } from '../../app/services/analysis';

jest.mock('../../app/services/analysis', () => ({
  AnalysisService: {
    getAnalysisResult: jest.fn(),
  },
}));

const mockGetAnalysisResult = AnalysisService.getAnalysisResult as jest.MockedFunction<
  typeof AnalysisService.getAnalysisResult
>;

function createWrapper() {
  const queryClient = new QueryClient({
    defaultOptions: {
      queries: {
        retry: false,
        gcTime: 0,
      },
    },
  });
  return function Wrapper(props: { children: React.ReactNode }) {
    return React.createElement(
      QueryClientProvider,
      { client: queryClient },
      props.children
    );
  };
}

describe('useAnalysisResult', () => {
  beforeEach(() => {
    jest.clearAllMocks();
    mockGetAnalysisResult.mockResolvedValue({
      success: true,
      data: {
        analysis_id: 'test-123',
        status: 'completed',
        biomarkers: [],
        clusters: [],
        insights: [],
        overall_score: 85,
        clinician_report_v1: {
          header: {
            report_version: 'v1',
            disclaimer_top: 'Generated by HealthIQ from commercial laboratory results.',
            footer_line: 'HealthIQ Clinician Summary Report - discussion aid.',
          },
          data_quality: {
            panel_completeness_present: 1,
            panel_completeness_expected: 1,
            lab_range_quality_by_primary_metric: [],
            confidence_caveat: 'Given available markers, interpret cautiously.',
            data_quality_passed: true,
          },
          sections: {
            page1: {
              primary_concern: 'Example concern',
              key_findings: ['Finding 1'],
              chains: [],
              top_hypothesis_line: 'Top hypothesis line.',
              confidence_and_missing_data: 'No critical data missing.',
            },
            root_cause: null,
            confirmatory_tests: [],
          },
          suppressed_confirmatory_tests: [],
        },
      },
      message: 'OK',
    });
  });

  it('fetches result exactly once per analysis_id', async () => {
    const Wrapper = createWrapper();
    const { result } = renderHook(
      () => useAnalysisResult('test-123'),
      { wrapper: Wrapper }
    );

    await waitFor(() => {
      expect(result.current.isSuccess).toBe(true);
    });

    expect(mockGetAnalysisResult).toHaveBeenCalledTimes(1);
    expect(mockGetAnalysisResult).toHaveBeenCalledWith('test-123');
  });

  it('does not fetch when analysisId is null', async () => {
    const Wrapper = createWrapper();
    renderHook(() => useAnalysisResult(null), { wrapper: Wrapper });

    await waitFor(() => {});

    expect(mockGetAnalysisResult).not.toHaveBeenCalled();
  });

  it('returns clinician_report_v1 payload when present', async () => {
    const Wrapper = createWrapper();
    const { result } = renderHook(() => useAnalysisResult('test-123'), { wrapper: Wrapper });

    await waitFor(() => {
      expect(result.current.isSuccess).toBe(true);
    });

    expect(result.current.data?.clinician_report_v1?.sections.page1.primary_concern).toBe('Example concern');
  });
});
