import React from 'react';
import { render, screen } from '@testing-library/react';
import ClinicianReportRenderer from '../../app/components/results/ClinicianReportRenderer';
import type { ClinicianReportV1 } from '../../app/types/analysis';

const sampleReport: ClinicianReportV1 = {
  header: {
    report_version: 'v1',
    disclaimer_top: 'Generated by HealthIQ from commercial laboratory results.',
    footer_line: 'HealthIQ Clinician Summary Report - discussion aid; not diagnostic or prescriptive.',
  },
  data_quality: {
    panel_completeness_present: 42,
    panel_completeness_expected: 55,
    lab_range_quality_by_primary_metric: ['homocysteine: one-sided (max only)'],
    confidence_caveat: 'Some hypotheses are limited by missing confirmatory markers.',
    data_quality_passed: false,
  },
  sections: {
    page1: {
      primary_concern: 'Homocysteine elevated (at_risk)',
      key_findings: ['Homocysteine exceeds lab upper bound on this panel.'],
      chains: ['signal_crp_high -> signal_homocysteine_high'],
      top_hypothesis_line: 'Top hypothesis: B12-associated pattern (confidence 0.60).',
      confidence_and_missing_data: 'Signal confidence 0.95; missing markers limit differentiation.',
    },
    root_cause: {
      signal_id: 'signal_homocysteine_elevation_context',
      signal_state: 'at_risk',
      signal_confidence: 0.95,
      primary_metric: 'homocysteine',
      hypotheses: [
        {
          hypothesis_id: 'hcy_b12_pattern_v1',
          title: 'B12-associated pattern',
          summary: 'Pattern can be consistent with reduced methylation capacity.',
          hypothesis_confidence: 0.6,
          ranking_rationale: 'Ranked #1 because MCV is elevated; MMA not tested.',
          evidence_for: [],
          evidence_against: [],
          missing_data: [],
          confirmatory_tests: [],
          safety_class: 'monitoring',
        },
      ],
    },
    confirmatory_tests: [
      {
        test_id: 'test_methylmalonic_acid_v1',
        display_name: 'Methylmalonic acid (MMA)',
        rationale: 'Consider discussing methylmalonic acid (MMA) testing with your clinician.',
      },
    ],
  },
  suppressed_confirmatory_tests: ['test_serum_vitamin_b12_v1'],
};

describe('ClinicianReportRenderer', () => {
  it('renders governed clinician report fields when payload is present', () => {
    render(<ClinicianReportRenderer report={sampleReport} />);

    expect(screen.getByText('Clinician Summary Report')).toBeInTheDocument();
    expect(screen.getByText('Primary concern:', { exact: false })).toBeInTheDocument();
    expect(screen.getByText('Homocysteine elevated (at_risk)')).toBeInTheDocument();
    expect(
      screen.getByText(/Top hypothesis: B12-associated pattern \(confidence 0.60\)\./),
    ).toBeInTheDocument();
    expect(screen.getByText('B12-associated pattern')).toBeInTheDocument();
    expect(screen.getByText(/Methylmalonic acid \(MMA\)/)).toBeInTheDocument();
    expect(screen.getByTestId('primary-concern-mode-distinct')).toBeInTheDocument();
  });

  it('surfaces technical tie-break mode, co-primaries, and policy stamp', () => {
    const report: ClinicianReportV1 = {
      ...sampleReport,
      sections: {
        ...sampleReport.sections,
        page1: {
          ...sampleReport.sections.page1,
          primary_concern_mode: 'technical_tiebreak_lead',
          co_primary_signal_ids: ['signal_a', 'signal_b'],
          ranking_policy_version: 'PRIMARY_CONCERN_AND_RANKED_AMBIGUITY_POLICY_V1+report-runtime-2a-v1',
        },
      },
    };
    render(<ClinicianReportRenderer report={report} />);
    expect(screen.getByTestId('primary-concern-mode-technical')).toBeInTheDocument();
    expect(screen.getByText(/Co-ranked signal identifiers:/)).toBeInTheDocument();
    expect(screen.getByText(/signal_a, signal_b/)).toBeInTheDocument();
    expect(screen.getByTestId('ranking-policy-version')).toHaveTextContent(
      'PRIMARY_CONCERN_AND_RANKED_AMBIGUITY_POLICY_V1+report-runtime-2a-v1',
    );
  });

  it('surfaces near-tie ambiguity mode and co-primaries', () => {
    const report: ClinicianReportV1 = {
      ...sampleReport,
      sections: {
        ...sampleReport.sections,
        page1: {
          ...sampleReport.sections.page1,
          primary_concern_mode: 'near_tie_ambiguity',
          co_primary_signal_ids: ['sig_x', 'sig_y'],
          ranking_policy_version: 'test-policy-v1',
        },
      },
    };
    render(<ClinicianReportRenderer report={report} />);
    expect(screen.getByTestId('primary-concern-mode-ambiguity')).toBeInTheDocument();
    expect(screen.getByText(/similarly supported on this panel/i)).toBeInTheDocument();
    expect(screen.getByText(/sig_x, sig_y/)).toBeInTheDocument();
  });

  it('degrades safely when clinician report payload is null', () => {
    render(<ClinicianReportRenderer report={null} />);
    expect(screen.getByText('Clinician Summary Report')).toBeInTheDocument();
    expect(
      screen.getByText('This analysis does not include a clinician report payload.'),
    ).toBeInTheDocument();
  });
});
