"""MED-FRAME-TREE-1 — regression tests for biomarker medical frame tree generator."""

from __future__ import annotations

import hashlib
import importlib.util
import os
import subprocess
import sys
from pathlib import Path

import yaml

_REPO = Path(__file__).resolve().parents[3]
_GENERATOR = _REPO / "knowledge_bus" / "tools" / "build_biomarker_medical_frame_tree.py"
_OUTPUT = _REPO / "docs" / "architecture" / "biomarker_medical_frame_tree.md"
_INDEX = _REPO / "knowledge_bus" / "governance" / "medical_frame_identity_index_v1.yaml"
_CATALOGUE = _REPO / "knowledge_bus" / "governance" / "context_modifier_catalogue_draft_v1.yaml"
_FIXED_UTC = "2026-06-03T12:00:00Z"


def _load_generator():
    spec = importlib.util.spec_from_file_location("build_biomarker_medical_frame_tree", _GENERATOR)
    mod = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(mod)
    return mod


def _index_ids() -> tuple[list[str], list[str]]:
    doc = yaml.safe_load(_INDEX.read_text(encoding="utf-8")) or {}
    families: list[str] = []
    frames: list[str] = []
    for fam in doc.get("signal_families") or []:
        if not isinstance(fam, dict):
            continue
        sfid = fam.get("signal_family_id")
        if sfid:
            families.append(str(sfid))
        for frame in fam.get("frames") or []:
            if isinstance(frame, dict) and frame.get("medical_frame_id"):
                frames.append(str(frame["medical_frame_id"]))
    return sorted(set(families)), sorted(set(frames))


def _catalogue_frame_links() -> dict[str, list[str]]:
    doc = yaml.safe_load(_CATALOGUE.read_text(encoding="utf-8")) or {}
    links: dict[str, list[str]] = {}
    for mod in doc.get("modifiers") or []:
        if not isinstance(mod, dict):
            continue
        mid = mod.get("modifier_id", "")
        for fid in (mod.get("applies_to") or {}).get("medical_frame_ids") or []:
            links.setdefault(str(fid), []).append(mid)
    return {k: sorted(set(v)) for k, v in links.items()}


def test_generator_runs_via_cli():
    env = {**os.environ, "MED_FRAME_TREE_UTC": _FIXED_UTC}
    proc = subprocess.run(
        [sys.executable, str(_GENERATOR)],
        cwd=_REPO,
        capture_output=True,
        text=True,
        env=env,
    )
    assert proc.returncode == 0, proc.stderr or proc.stdout
    assert _OUTPUT.is_file()


def test_generated_tree_contains_all_indexed_families_and_frames():
    text = _OUTPUT.read_text(encoding="utf-8")
    families, frames = _index_ids()
    for sfid in families:
        assert sfid in text, f"missing family {sfid}"
    for fid in frames:
        assert fid in text, f"missing frame {fid}"


def test_generated_tree_contains_linked_context_modifiers():
    text = _OUTPUT.read_text(encoding="utf-8")
    for fid, mods in _catalogue_frame_links().items():
        assert fid in text
        for mid in mods:
            assert mid in text, f"missing modifier {mid} for frame {fid}"


def test_generated_tree_declares_non_authoritative():
    text = _OUTPUT.read_text(encoding="utf-8")
    assert "Do not edit this file manually" in text
    assert "generated from governed" in text.lower() or "Generated" in text


def test_generator_is_deterministic_with_fixed_utc():
    mod = _load_generator()
    env_utc = _FIXED_UTC
    os.environ["MED_FRAME_TREE_UTC"] = env_utc
    try:
        a = mod.generate(output_path=_OUTPUT, dry_run=True)
        b = mod.generate(output_path=_OUTPUT, dry_run=True)
    finally:
        os.environ.pop("MED_FRAME_TREE_UTC", None)
    assert a == b


def test_generator_does_not_modify_governance_sources():
    before = {p: hashlib.sha256(p.read_bytes()).hexdigest() for p in [_INDEX, _CATALOGUE]}
    mod = _load_generator()
    os.environ["MED_FRAME_TREE_UTC"] = _FIXED_UTC
    try:
        mod.generate(output_path=_OUTPUT, dry_run=True)
    finally:
        os.environ.pop("MED_FRAME_TREE_UTC", None)
    after = {p: hashlib.sha256(p.read_bytes()).hexdigest() for p in [_INDEX, _CATALOGUE]}
    assert before == after


def test_generator_rejects_output_outside_docs_architecture(tmp_path):
    mod = _load_generator()
    bad = tmp_path / "elsewhere" / "tree.md"
    bad.parent.mkdir(parents=True)
    proc = subprocess.run(
        [sys.executable, str(_GENERATOR), "--output", str(bad)],
        cwd=_REPO,
        capture_output=True,
        text=True,
    )
    assert proc.returncode == 2
